name: SimpleWebServer
description: 'A simple web server'
author: 'CptGummiball'
version: '${project.version}'
main: org.cptgum.simplewebserver.main
api-version: '1.20'
load: POSTWORLD

commands:
  sws:
    description: 'Manage MCDealer functionalities'
    usage: /sws <start|stop|restart|link>
    permission: sws.use

permissions:
  sws.use:
    description: 'Allows general access to the /sws command.'
    default: true
    sws.admin:
      description: 'Access to all commands.'
      default: op
    sws.link:
      description: 'Show the link to the web server.'
      default: true
